---
abstract: 'Auto-completion for Perl'
author:
  - 'Moritz Onken <onken@netcubed.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-IntelliPerl
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/monken/Devel-IntelliPerl/tree/master
version: 0.01
